module.exports = {
  ADD_SECTION: 'ADD_SECTION',
  EDIT_GENERAL: 'EDIT_GENERAL',
  EDIT_GIST: 'EDIT_GIST',
  EDIT_SECTION: 'EDIT_SECTION',
  EDIT_TOKEN: 'EDIT_TOKEN',
  IMPORT: 'IMPORT',
  LOADING_GIST: 'LOADING_GIST',
  LOADING_GIST_FAILURE: 'LOADING_GIST_FAILURE',
  LOADING_GIST_SUCCESS: 'LOADING_GIST_SUCCESS',
  REMOVE_SECTION: 'REMOVE_SECTION',
  UPDATING_GIST: 'UPDATING_GIST',
  UPDATING_GIST_FAILURE: 'UPDATING_GIST_FAILURE',
  UPDATING_GIST_SUCCESS: 'UPDATING_GIST_SUCCESS'
}
